# Site settings
title: American Remodeling Enterprises HR Portal
email: hr@americanremodelingenterprises.com
description: >-
  Secure HR onboarding platform for American Remodeling Enterprises and Epoxy Floor Experts
baseurl: "/hr-onboarding" # the subpath of your site, e.g. /blog
url: "https://tim-amredev.github.io" # the base hostname & protocol for your site
github_username: tim-amredev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections for different types of content
collections:
  policies:
    output: true
  trainings:
    output: true
  forms:
    output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

